apiVersion: v1
kind: Service
metadata:
  name: my-cs
  labels:
    app: my-cs
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: my-cs
  type: NodePort
