apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: local-path
