replicaCount: 3

image:
  repository: ghcr.io/Endrius-Albert/bookcatalog
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: bookcatalog.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /api/health
    port: 8000

readinessProbe:
  httpGet:
    path: /api/health
    port: 8000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: config-volume
    configMap:
      name: app-config

volumeMounts:
  - name: config-volume
    mountPath: /app/config

nodeSelector: {}

tolerations: []

affinity: {}

environmentVariables:
  - name: DJANGO_DEBUG
    value: "false"
  - name: DJANGO_ALLOWED_HOSTS
    value: "*"

loadSecretsFrom: bookcatalog-db
